Repository Team-Binions/Team-Binions, pull requests merged in 2024-05, with the labels that each got.

#15 [FEATURE]configDTO + lombok dependency 추가
  .gradle/8.4/executionHistory/executionHistory.bin
  .gradle/8.4/executionHistory/executionHistory.lock
  .gradle/8.4/fileHashes/fileHashes.bin
  .gradle/8.4/fileHashes/fileHashes.lock
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .idea/compiler.xml
  .idea/modules.xml
  .idea/modules/beanions.main.iml
  build.gradle
  src/main/java/com/beanions/admin/controller/adminControllerTemp.java
  src/main/java/com/beanions/admin/service/adminServiceTemp.java
  src/main/java/com/beanions/auth/controller/authControllerTemp.java
  src/main/java/com/beanions/auth/model/service/authServiceTemp.java
  src/main/java/com/beanions/common/MemberRole.java
  src/main/java/com/beanions/common/controller/MainController.java
  src/main/java/com/beanions/common/dto/CommentsDTO.java
  src/main/java/com/beanions/common/dto/FilesDTO.java
  src/main/java/com/beanions/common/dto/MembersDTO.java
  src/main/java/com/beanions/common/dto/PostDTO.java
  src/main/java/com/beanions/common/dto/SchedulesDTO.java
  src/main/java/com/beanions/config/BeanionsApplication.java
  src/main/java/com/beanions/user/controller/userControllerTemp.java
  src/main/java/com/beanions/user/service/userServiceTemp.java
  src/main/resources/templates/user/userMain.html
Labels: feature

#22 [FEATURE/DEFAULTCOMMONCSS]Poppins font파일 추가
  src/main/resources/assets/css/font/Poppins-Regular.ttf
Labels: enhancement

#38 [FEATURE][MAIN]메인페이지 추가 및 mainController내 main페이지 연결 경로 수정 & default.css 기본폰트 설정 추가
  src/main/java/com/beanions/common/controller/MainController.java
  src/main/resources/assets/css/default.css
  src/main/resources/assets/css/user/common.css
  src/main/resources/templates/user/main.html
Labels: feature

#35 [Feature][freeBoard] 예신 수다방 조회 구현 ( CUD 구현중)
  build.gradle
  src/main/java/com/beanions/common/dao/user/FreeBoardMapper.java
  src/main/java/com/beanions/common/dao/user/UserMapper.java
  src/main/java/com/beanions/common/dto/MainCategoryDTO.java
  src/main/java/com/beanions/common/dto/PostAndMemberDTO.java
  src/main/java/com/beanions/common/dto/SearchDTO.java
  src/main/java/com/beanions/common/dto/SubCategoryDTO.java
  src/main/java/com/beanions/common/paging/Pagination.java
  src/main/java/com/beanions/common/paging/PagingResponse.java
  src/main/java/com/beanions/user/controller/FreeBoardController.java
  src/main/java/com/beanions/user/service/FreeBoardService.java
  src/main/resources/mapper/FreeBoardMapper.xml
  src/main/resources/templates/user/postRegist.html
  src/main/resources/templates/user/yesinDetail.html
  src/main/resources/templates/user/yesinList.html
Labels: feature

#52 [FEATURE][MAIN] 메인 페이지 HTML 수정 및 main.css 추가
  src/main/resources/assets/css/user/main.css
  src/main/resources/templates/user/main.html
Labels: feature

#56 [boardeun]게시판 등록 카테고리 작성중
  src/main/java/com/beanions/common/dao/user/board/FreeBoardMapper.java
  src/main/java/com/beanions/user/controller/board/FreeBoardController.java
  src/main/java/com/beanions/user/service/board/FreeBoardService.java
  src/main/resources/mapper/userBoard/FreeBoardMapper.xml
  src/main/resources/templates/user/board/postRegist.html
  src/main/resources/templates/user/board/yesinList.html
Labels: feature

#62 [Feature][post]board등록 기능
  src/main/java/com/beanions/common/dao/user/board/FreeBoardMapper.java
  src/main/java/com/beanions/user/controller/board/FreeBoardController.java
  src/main/java/com/beanions/user/service/board/FreeBoardService.java
  src/main/resources/mapper/userBoard/FreeBoardMapper.xml
  src/main/resources/templates/user/board/freeboardmodify.html
  src/main/resources/templates/user/board/noticeboard.html
  src/main/resources/templates/user/board/noticeboarddetail.html
  src/main/resources/templates/user/board/postRegist.html
  src/main/resources/templates/user/board/yesinDetail.html
  src/main/resources/templates/user/board/yesinList.html
  src/main/resources/templates/user/layout/header.html
Labels: feature

#64 [FEATURE][ADMIN] 관리자 게시판 기능 수정 및 삭제 모달 추가
  src/main/java/com/beanions/admin/controller/AdminController.java
  src/main/java/com/beanions/admin/controller/AdminMainController.java
  src/main/java/com/beanions/admin/service/MemberService.java
  src/main/resources/assets/css/admin/adminPost.css
  src/main/resources/assets/css/admin/common.css
  src/main/resources/mapper/AdminMapper.xml
  src/main/resources/templates/admin/footer.html
  src/main/resources/templates/admin/layout.html
  src/main/resources/templates/admin/magazine/detail.html
  src/main/resources/templates/admin/magazine/list.html
  src/main/resources/templates/admin/magazine/regist.html
  src/main/resources/templates/admin/magazine/update.html
  src/main/resources/templates/admin/main/dashBoard.html
  src/main/resources/templates/admin/notice/detail.html
  src/main/resources/templates/admin/notice/list.html
  src/main/resources/templates/admin/notice/regist.html
  src/main/resources/templates/admin/notice/update.html
  src/main/resources/templates/admin/post/detail.html
  src/main/resources/templates/admin/post/freeDetail.html
  src/main/resources/templates/admin/post/list.html
  src/main/resources/templates/admin/post/update.html
Labels: feature

#65 [FEATURE][MYPAGE] 마이페이지 레이아웃 및 기능 작업
  src/main/java/com/beanions/common/dao/user/MyPageMapper.java
  src/main/java/com/beanions/common/dto/MyPageDTO.java
  src/main/java/com/beanions/user/controller/MyPageController.java
  src/main/java/com/beanions/user/service/MyPageService.java
  src/main/resources/assets/css/user/mypage.css
  src/main/resources/mapper/MyPageMapper.xml
  src/main/resources/templates/user/mypage/mypageComment.html
  src/main/resources/templates/user/mypage/mypageFree.html
  src/main/resources/templates/user/mypage/mypageMain.html
  src/main/resources/templates/user/mypage/mypageReview.html
Labels: feature

#66 [FEATURE][board] 게시물 관련 CRUD 구현, 폴더 정리에 따른 board폴더 생성,
  src/main/java/com/beanions/common/dao/user/board/FreeBoardMapper.java
  src/main/java/com/beanions/common/dao/user/board/NoticeMapper.java
  src/main/java/com/beanions/user/controller/FreeBoardController.java
  src/main/java/com/beanions/user/controller/NoticeController.java
  src/main/java/com/beanions/user/controller/board/FreeBoardController.java
  src/main/java/com/beanions/user/controller/board/NoticeController.java
  src/main/java/com/beanions/user/service/board/FreeBoardService.java
  src/main/java/com/beanions/user/service/board/NoticeService.java
  src/main/resources/mapper/userBoard/FreeBoardMapper.xml
  src/main/resources/mapper/userBoard/NoticeMapper.xml
  src/main/resources/templates/user/board/freeboardmodify.html
  src/main/resources/templates/user/board/noticeboard.html
  src/main/resources/templates/user/board/noticeboarddetail.html
  src/main/resources/templates/user/board/postRegist.html
  src/main/resources/templates/user/board/yesinDetail.html
  src/main/resources/templates/user/board/yesinList.html
  src/main/resources/templates/user/layout/header.html
  src/main/resources/templates/user/modify.html
  src/main/resources/templates/user/postRegist.html
  src/main/resources/templates/user/yesinDetail.html
  src/main/resources/templates/user/yesinList.html
Labels: feature

#59 [FEATURE][SIGNUP]회원가입 기능
  src/main/java/com/beanions/common/controller/MainController.java
  src/main/java/com/beanions/common/controller/SignupController.java
  src/main/java/com/beanions/common/dao/signup/SignupMapper.java
  src/main/java/com/beanions/common/dto/MembersDTO.java
  src/main/java/com/beanions/common/service/SignupService.java
  src/main/resources/assets/css/user/signup.css
  src/main/resources/assets/js/signup.js
  src/main/resources/mapper/SignupMapper.xml
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/main.html
  src/main/resources/templates/user/signup.html
Labels: feature

#67 [FEATURE][FREEMAGAZINEEUN]이름 수정
  src/main/java/com/beanions/common/dao/user/board/FreeBoardMapper.java
  src/main/java/com/beanions/common/dao/user/board/MagazineMapper.java
  src/main/java/com/beanions/user/controller/board/FreeBoardController.java
  src/main/java/com/beanions/user/controller/board/MagazineController.java
  src/main/java/com/beanions/user/service/board/FreeBoardService.java
  src/main/java/com/beanions/user/service/board/MagazineService.java
  src/main/resources/mapper/userBoard/FreeBoardMapper.xml
  src/main/resources/mapper/userBoard/MagazineMapper.xml
  src/main/resources/templates/user/board/magazineList.html
Labels: feature

#73 [FEATURE][NOTICE&REVIEW]공지사항, 리뷰 기본 css 추가
  src/main/resources/templates/user/board/noticeDetail.html
  src/main/resources/templates/user/board/noticeList.html
  src/main/resources/templates/user/board/reviewDetail.html
  src/main/resources/templates/user/board/reviewList.html
  src/main/resources/templates/user/board/reviewModify.html
  src/main/resources/templates/user/board/reviewRegist.html
Labels: feature

#72 [FEATURE][EUN] 자유, 매거진 게시판 CSS 적용
  src/main/resources/mapper/userBoard/FreeBoardMapper.xml
  src/main/resources/mapper/userBoard/MagazineMapper.xml
  src/main/resources/mapper/userBoard/NoticeMapper.xml
  src/main/resources/templates/user/board/freeDetail.html
  src/main/resources/templates/user/board/freeList.html
  src/main/resources/templates/user/board/freeModify.html
  src/main/resources/templates/user/board/freeRegist.html
  src/main/resources/templates/user/board/magazineDetail.html
  src/main/resources/templates/user/board/magazineList.html
  src/main/resources/templates/user/board/reviewList.html
  src/main/resources/templates/user/layout/header.html
Labels: feature

#74 [FEATURE][MYPAGE] - 마이페이지 > 나의 글 메뉴(예리뷰/예수다/댓글) READ 기능 완료
  src/main/java/com/beanions/common/dao/user/MyPageMapper.java
  src/main/java/com/beanions/common/dto/MembersDTO.java
  src/main/java/com/beanions/common/dto/MyPageDTO.java
  src/main/java/com/beanions/user/controller/MyPageController.java
  src/main/java/com/beanions/user/service/MyPageService.java
  src/main/resources/assets/css/user/mypage.css
  src/main/resources/mapper/MyPageMapper.xml
  src/main/resources/templates/user/mypage/mypageComment.html
  src/main/resources/templates/user/mypage/mypageFree.html
  src/main/resources/templates/user/mypage/mypageReview.html
Labels: feature

#75 [FEATURE][ADMIN] 관리자 페이지 레이아웃 수정 및 상세페이지 기본 CSS 적용
  src/main/resources/assets/css/admin/adminPost.css
  src/main/resources/assets/css/admin/common.css
  src/main/resources/templates/admin/header.html
  src/main/resources/templates/admin/magazine/detail.html
  src/main/resources/templates/admin/magazine/list.html
  src/main/resources/templates/admin/magazine/regist.html
  src/main/resources/templates/admin/magazine/update.html
  src/main/resources/templates/admin/main/dashBoard.html
  src/main/resources/templates/admin/notice/detail.html
  src/main/resources/templates/admin/notice/list.html
  src/main/resources/templates/admin/notice/regist.html
  src/main/resources/templates/admin/notice/update.html
  src/main/resources/templates/admin/post/detail.html
  src/main/resources/templates/admin/post/list.html
  src/main/resources/templates/admin/sidebar.html
Labels: feature

#82 [FEATURE][EUN] 댓글 뷰, 자유 게시판 MODIFY연결 수정
  src/main/java/com/beanions/user/controller/board/FreeBoardController.java
  src/main/resources/mapper/userBoard/FreeBoardMapper.xml
  src/main/resources/templates/user/board/freeDetail.html
  src/main/resources/templates/user/board/freeList.html
  src/main/resources/templates/user/board/freeModify.html
  src/main/resources/templates/user/board/freeRegist.html
  src/main/resources/templates/user/board/reviewList.html
Labels: feature

#86 [FEATURE][ADMIN] 회원정보 수정 및 삭제
  src/main/java/com/beanions/admin/controller/AdminController.java
  src/main/java/com/beanions/admin/service/MemberService.java
  src/main/java/com/beanions/common/dao/admin/AdminMapper.java
  src/main/resources/assets/css/admin/membersCss.css
  src/main/resources/mapper/AdminMapper.xml
  src/main/resources/templates/admin/member/membersDelete.html
  src/main/resources/templates/admin/member/membersDetail.html
  src/main/resources/templates/admin/member/membersList.html
  src/main/resources/templates/admin/member/membersModify.html
  src/main/resources/templates/admin/sidebar.html
Labels: feature

#81 [FEATURE][ADMIN] 리뷰 승인(미승인) 컬럼 추가에 따른 상태 변경 기능 수정
  src/main/java/com/beanions/admin/controller/AdminMainController.java
  src/main/java/com/beanions/admin/service/AdminService.java
  src/main/java/com/beanions/common/dao/admin/AdminMapper.java
  src/main/java/com/beanions/common/dto/AdminPostDTO.java
  src/main/resources/assets/css/admin/adminPost.css
  src/main/resources/assets/css/admin/common.css
  src/main/resources/mapper/AdminMapper.xml
  src/main/resources/templates/admin/header.html
  src/main/resources/templates/admin/main/dashBoard.html
  src/main/resources/templates/admin/post/detail.html
  src/main/resources/templates/admin/post/list.html
  src/main/resources/templates/admin/sidebar.html
Labels: feature

#83 [FEATURE][board] 댓글 뷰 추가, 글쓰기 뷰 수정,
  src/main/java/com/beanions/user/controller/board/FreeBoardController.java
  src/main/resources/mapper/userBoard/FreeBoardMapper.xml
  src/main/resources/templates/user/board/freeDetail.html
  src/main/resources/templates/user/board/freeList.html
  src/main/resources/templates/user/board/freeModify.html
  src/main/resources/templates/user/board/freeRegist.html
  src/main/resources/templates/user/board/reviewList.html
Labels: feature

#90 [FEATURE][EUN] 조회수 뷰 추가, 리뷰 매핑
  src/main/java/com/beanions/common/dao/user/board/ReviewMapper.java
  src/main/java/com/beanions/common/dto/PostAndMemberDTO.java
  src/main/java/com/beanions/user/controller/board/FreeBoardController.java
  src/main/java/com/beanions/user/controller/board/ReviewController.java
  src/main/java/com/beanions/user/service/board/ReviewService.java
  src/main/resources/mapper/userBoard/FreeBoardMapper.xml
  src/main/resources/mapper/userBoard/ReviewMapper.xml
  src/main/resources/templates/user/board/freeList.html
  src/main/resources/templates/user/board/reviewList.html
Labels: feature

#91 [FEATURE][BOARD] 상세페이지 닉네임
  src/main/java/com/beanions/user/controller/board/FreeBoardController.java
  src/main/java/com/beanions/user/controller/board/ReviewController.java
  src/main/resources/templates/user/board/reviewModify.html
Labels: feature

#94 [FEATURE][BOARD] 상세페이지 닉네임 추가
  src/main/resources/mapper/userBoard/FreeBoardMapper.xml
  src/main/resources/mapper/userBoard/MagazineMapper.xml
  src/main/resources/mapper/userBoard/NoticeMapper.xml
  src/main/resources/mapper/userBoard/ReviewMapper.xml
  src/main/resources/templates/user/board/magazineDetail.html
  src/main/resources/templates/user/board/noticeDetail.html
Labels: feature

#87 [FEATURE][SIGNUP] 회원가입 0513 피드백
  src/main/java/com/beanions/common/controller/SignupController.java
  src/main/java/com/beanions/common/service/SignupService.java
  src/main/resources/assets/css/user/signup.css
  src/main/resources/assets/js/signup.js
  src/main/resources/templates/user/signup.html
Labels: feature

#95 [FEATURE][ADMIN] 관리자 공지사항 & 매거진 관리 전체조회 페이지, 상세페이지 CSS 수정
  src/main/resources/assets/css/admin/common.css
  src/main/resources/templates/admin/magazine/detail.html
  src/main/resources/templates/admin/magazine/list.html
  src/main/resources/templates/admin/main/dashBoard.html
  src/main/resources/templates/admin/notice/detail.html
  src/main/resources/templates/admin/notice/list.html
  src/main/resources/templates/admin/post/list.html
  src/main/resources/templates/admin/sidebar.html
Labels: feature

#96 [FEATURE][BOARD] 자유게시판 삭제, 수정 맵핑 수정, 상세페이지 닉네임
  src/main/java/com/beanions/common/dao/user/board/ReviewMapper.java
  src/main/java/com/beanions/common/dto/PostAndMemberDTO.java
  src/main/java/com/beanions/user/controller/board/FreeBoardController.java
  src/main/java/com/beanions/user/controller/board/ReviewController.java
  src/main/java/com/beanions/user/service/board/ReviewService.java
  src/main/resources/mapper/userBoard/FreeBoardMapper.xml
  src/main/resources/mapper/userBoard/MagazineMapper.xml
  src/main/resources/mapper/userBoard/NoticeMapper.xml
  src/main/resources/mapper/userBoard/ReviewMapper.xml
  src/main/resources/templates/user/board/freeList.html
  src/main/resources/templates/user/board/magazineDetail.html
  src/main/resources/templates/user/board/noticeDetail.html
  src/main/resources/templates/user/board/reviewList.html
Labels: feature

#92 [FEATURE][MYPAGE] MYINFO(회원 정보 수정) 페이지 및 관련 아이콘 이미지 경로 연결
  src/main/java/com/beanions/common/controller/MainController.java
  src/main/resources/assets/css/user/mypage.css
  src/main/resources/templates/user/mypage/mypageComment.html
  src/main/resources/templates/user/mypage/mypageFree.html
  src/main/resources/templates/user/mypage/mypageMyinfo.html
  src/main/resources/templates/user/mypage/mypageReview.html
Labels: feature

#100 [FEATURE][ADMIN] 공지사항, 매거진 각 CRUD 페이지 CSS 및 기능 수정
  src/main/resources/assets/css/admin/adminPost.css
  src/main/resources/assets/css/admin/common.css
  src/main/resources/mapper/AdminMapper.xml
  src/main/resources/templates/admin/magazine/regist.html
  src/main/resources/templates/admin/magazine/update.html
  src/main/resources/templates/admin/main/dashBoard.html
  src/main/resources/templates/admin/notice/regist.html
  src/main/resources/templates/admin/notice/update.html
Labels: feature

#102 [FEATURE][MYPAGE] 마이페이지 > 스케쥴 관리 CRUD 작업
  src/main/java/com/beanions/common/dao/user/MyPageMapper.java
  src/main/java/com/beanions/user/controller/MyPageController.java
  src/main/java/com/beanions/user/service/MyPageService.java
  src/main/resources/assets/css/user/mypage.css
  src/main/resources/assets/images/common/icon_edit_hover.png
  src/main/resources/assets/images/common/icon_edit_white.png
  src/main/resources/mapper/MyPageMapper.xml
  src/main/resources/templates/user/mypage/mypageSchedule.html
  src/main/resources/templates/user/mypage/mypageScheduleDetail.html
  src/main/resources/templates/user/mypage/mypageScheduleManage.html
  src/main/resources/templates/user/mypage/mypageScheduleRegister.html
Labels: feature

#103 [FEATURE][BOARD] 공지사항 CSS, 페이지네이션, 조회수 기능 추가
  src/main/java/com/beanions/common/dao/user/board/FreeBoardMapper.java
  src/main/java/com/beanions/common/dao/user/board/MagazineMapper.java
  src/main/java/com/beanions/common/dao/user/board/ReviewMapper.java
  src/main/java/com/beanions/common/dto/Page.java
  src/main/java/com/beanions/common/dto/PageMaker.java
  src/main/java/com/beanions/common/dto/PostDTO.java
  src/main/java/com/beanions/user/controller/board/PageController.java
  src/main/java/com/beanions/user/service/board/FreeBoardService.java
  src/main/java/com/beanions/user/service/board/MagazineService.java
  src/main/java/com/beanions/user/service/board/ReviewService.java
  src/main/resources/assets/css/user/board/notice.css
  src/main/resources/mapper/userBoard/FreeBoardMapper.xml
  src/main/resources/mapper/userBoard/MagazineMapper.xml
  src/main/resources/templates/user/board/freeDetail.html
  src/main/resources/templates/user/board/freeList.html
  src/main/resources/templates/user/board/magazineList.html
  src/main/resources/templates/user/board/noticeDetail.html
  src/main/resources/templates/user/board/noticeList.html
  src/main/resources/templates/user/board/reviewList.html
  src/main/resources/templates/user/board/reviewModify.html
Labels: feature

#120 [FEATUR][ADMINDELETEMEMBER] 수정 및 삭제 완료
  src/main/java/com/beanions/admin/controller/AdminController.java
  src/main/java/com/beanions/admin/service/MemberService.java
  src/main/java/com/beanions/common/dao/admin/AdminMapper.java
  src/main/java/com/beanions/common/dto/MembersDTO.java
  src/main/resources/assets/css/admin/membersCss.css
  src/main/resources/mapper/AdminMapper.xml
  src/main/resources/templates/admin/member/membersDetail.html
  src/main/resources/templates/admin/member/membersList.html
  src/main/resources/templates/admin/member/membersModify.html
Labels: feature

#113 [FEATURE][ADMIN]관리자 dashBoard 기능 구현
  src/main/java/com/beanions/admin/controller/AdminBoardController.java
  src/main/java/com/beanions/admin/controller/AdminMainController.java
  src/main/java/com/beanions/admin/service/AdminService.java
  src/main/java/com/beanions/common/controller/MainController.java
  src/main/java/com/beanions/common/dao/admin/AdminMapper.java
  src/main/java/com/beanions/common/dto/AdminMainDTO.java
  src/main/resources/assets/css/admin/common.css
  src/main/resources/mapper/AdminMapper.xml
  src/main/resources/templates/admin/main/dashBoard.html
Labels: feature

#110 [FEATURE][LOGIN] 아이디/비밀번호 찾기
  src/main/java/com/beanions/auth/controller/AuthController.java
  src/main/java/com/beanions/auth/model/service/AuthService.java
  src/main/java/com/beanions/common/controller/LoginService.java
  src/main/java/com/beanions/common/controller/MainController.java
  src/main/java/com/beanions/common/controller/SignupController.java
  src/main/java/com/beanions/common/dao/signup/SignupMapper.java
  src/main/java/com/beanions/common/dao/user/UserMapper.java
  src/main/java/com/beanions/common/service/LoginService.java
  src/main/java/com/beanions/common/service/MailService.java
  src/main/java/com/beanions/common/service/SignupService.java
  src/main/java/com/beanions/config/SecurityConfig.java
  src/main/resources/assets/css/user/login.css
  src/main/resources/assets/css/user/signup.css
  src/main/resources/assets/js/forgetInfo.js
  src/main/resources/assets/js/signup.js
  src/main/resources/mapper/UserMapper.xml
  src/main/resources/templates/auth/forgetInfo.html
  src/main/resources/templates/auth/login.html
  src/main/resources/templates/user/signup.html
Labels: feature

#112 [FEATURE][MAIN] 메인 페이지 레이아웃 및 DB연결 작업
  src/main/java/com/beanions/common/controller/MainController.java
  src/main/java/com/beanions/common/controller/MainService.java
  src/main/java/com/beanions/common/dao/user/MainMapper.java
  src/main/resources/assets/css/user/main.css
  src/main/resources/assets/images/common/icon_mail.svg
  src/main/resources/assets/images/main/KakaoTalk_20230405_053202431_12.jpg
  src/main/resources/assets/images/main/KakaoTalk_20230714_011813075_13.jpg
  src/main/resources/assets/images/main/P1034264.jpg
  src/main/resources/assets/images/main/P1045088.jpg
  src/main/resources/assets/images/main/banner01.jpg
  src/main/resources/assets/images/main/banner02.jpg
  src/main/resources/assets/images/main/contactIllust.svg
  src/main/resources/assets/images/main/viewMagazineImageTemp.jpg
  src/main/resources/assets/images/main/viewNoticeImageTemp.jpg
  src/main/resources/assets/images/main/viewReviewImageTemp.jpg
  src/main/resources/assets/js/main.js
  src/main/resources/mapper/MainMapper.xml
  src/main/resources/templates/user/main.html
Labels: feature

#116 [FEATURE][COMMONSETTING] common.css 속성 및 아이콘 이미지 추가 & common.js 추가
  src/main/resources/assets/css/user/common.css
  src/main/resources/assets/images/common/icon_arrow_left_white.svg
  src/main/resources/assets/images/common/icon_arrow_right_white.svg
  src/main/resources/assets/js/common.js
  src/main/resources/templates/user/layout/footer.html
  src/main/resources/templates/user/layout/header.html
Labels: feature

#125 [FEATURE][BOARDSTATUS] 승인 여부, 활성화 여부에 따른 게시물 정보 수정
  src/main/java/com/beanions/board/common/dto/PostAndMemberDTO.java
  src/main/java/com/beanions/board/review/controller/ReviewController.java
  src/main/resources/assets/css/user/board/free.css
  src/main/resources/assets/css/user/board/notice.css
  src/main/resources/assets/css/user/board/review.css
  src/main/resources/mapper/board/FreeBoardMapper.xml
  src/main/resources/mapper/board/ReviewMapper.xml
  src/main/resources/templates/user/board/freeDetail.html
  src/main/resources/templates/user/board/freeList.html
  src/main/resources/templates/user/board/noticeList.html
  src/main/resources/templates/user/board/reviewDetail.html
  src/main/resources/templates/user/board/reviewList.html
Labels: feature

#127 [Feature][eun] 페이지 네이션 기능 추가중
  src/main/java/com/beanions/board/free/controller/FreeBoardController.java
  src/main/java/com/beanions/board/free/dao/FreeBoardMapper.java
  src/main/java/com/beanions/board/free/service/FreeBoardService.java
  src/main/java/com/beanions/common/dto/SearchDTO.java
  src/main/java/com/beanions/common/paging/PagingResponse.java
  src/main/java/com/beanions/config/SecurityConfig.java
  src/main/resources/mapper/board/FreeBoardMapper.xml
  src/main/resources/templates/user/board/freeList.html
Labels: feature

#129 [FEATURE][ADMIN] 회원 상세 조회 이슈
  src/main/java/com/beanions/admin/controller/AdminController.java
  src/main/java/com/beanions/admin/dao/AdminMapper.java
  src/main/java/com/beanions/admin/service/AdminMemberService.java
  src/main/resources/assets/css/admin/adminPost.css
  src/main/resources/mapper/admin/AdminMapper.xml
  src/main/resources/templates/admin/member/membersDetail.html
Labels: feature

#126 [FEATURE][ADMIN] 관리자 메인페이지 예피셜 게시물 수 조회 & 로그인한 사용자 정보 헤더에 적용
  src/main/java/com/beanions/admin/dto/AdminMainDTO.java
  src/main/resources/assets/css/admin/common.css
  src/main/resources/mapper/admin/AdminMapper.xml
  src/main/resources/templates/admin/header.html
  src/main/resources/templates/admin/main/dashBoard.html
Labels: feature

#128 [Feature][board] 승인 여부, 활성화 여부에 따른 게시물 정보 수정, 페이지네이션 기능 추가
  src/main/java/com/beanions/board/common/dto/PostAndMemberDTO.java
  src/main/java/com/beanions/board/free/controller/FreeBoardController.java
  src/main/java/com/beanions/board/free/dao/FreeBoardMapper.java
  src/main/java/com/beanions/board/free/service/FreeBoardService.java
  src/main/java/com/beanions/board/review/controller/ReviewController.java
  src/main/java/com/beanions/common/dto/SearchDTO.java
  src/main/java/com/beanions/common/paging/PagingResponse.java
  src/main/java/com/beanions/config/SecurityConfig.java
  src/main/resources/assets/css/user/board/free.css
  src/main/resources/assets/css/user/board/notice.css
  src/main/resources/assets/css/user/board/review.css
  src/main/resources/mapper/board/FreeBoardMapper.xml
  src/main/resources/mapper/board/ReviewMapper.xml
  src/main/resources/templates/user/board/freeDetail.html
  src/main/resources/templates/user/board/freeList.html
  src/main/resources/templates/user/board/noticeList.html
  src/main/resources/templates/user/board/reviewDetail.html
  src/main/resources/templates/user/board/reviewList.html
Labels: feature

#135 [Feature][eun] 페이지네이션 구현중
  src/main/java/com/beanions/board/magazine/dao/MagazineMapper.java
  src/main/resources/mapper/board/MagazineMapper.xml
  src/main/resources/templates/user/board/freeList.html
Labels: feature

#136 [FEATURE][BOARD]글쓰기 기능, CSS 수정, 정렬 기능 수정
  src/main/java/com/beanions/board/free/controller/FreeBoardController.java
  src/main/java/com/beanions/board/review/controller/ReviewController.java
  src/main/java/com/beanions/common/dto/SearchDTO.java
  src/main/resources/assets/css/user/board/free.css
  src/main/resources/assets/css/user/board/magazine.css
  src/main/resources/assets/css/user/board/notice.css
  src/main/resources/assets/css/user/board/regist.css
  src/main/resources/assets/css/user/board/review.css
  src/main/resources/mapper/board/FreeBoardMapper.xml
  src/main/resources/mapper/board/ReviewMapper.xml
  src/main/resources/templates/user/board/freeList.html
  src/main/resources/templates/user/board/freeRegist.html
  src/main/resources/templates/user/board/noticeDetail.html
  src/main/resources/templates/user/board/noticeList.html
Labels: feature

#138 [FEATURE][BOARD]글쓰기 기능, CSS 수정, 정렬 기능 수정
  src/main/java/com/beanions/board/free/controller/FreeBoardController.java
  src/main/java/com/beanions/board/review/controller/ReviewController.java
  src/main/java/com/beanions/common/dto/SearchDTO.java
  src/main/resources/assets/css/user/board/free.css
  src/main/resources/assets/css/user/board/magazine.css
  src/main/resources/assets/css/user/board/notice.css
  src/main/resources/assets/css/user/board/regist.css
  src/main/resources/assets/css/user/board/review.css
  src/main/resources/mapper/board/FreeBoardMapper.xml
  src/main/resources/mapper/board/ReviewMapper.xml
  src/main/resources/templates/user/board/freeDetail.html
  src/main/resources/templates/user/board/freeList.html
  src/main/resources/templates/user/board/freeRegist.html
  src/main/resources/templates/user/board/noticeDetail.html
  src/main/resources/templates/user/board/noticeList.html
Labels: feature

#141 [FEATURE][COMMONSETTING] 마이페이지 버튼 관련 common.css 속성 및 아이콘 이미지 추가
  src/main/resources/assets/css/user/common.css
  src/main/resources/templates/user/layout/header.html
Labels: feature

#139 [FEATURE][MYPAGESESSION] 마이페이지 세션 정보 + 의존성 NULL 이슈 해결
  src/main/java/com/beanions/mypage/controller/MyPageController.java
  src/main/java/com/beanions/mypage/dao/MyPageMapper.java
  src/main/java/com/beanions/mypage/dto/SchedulesDTO.java
  src/main/java/com/beanions/mypage/service/MyPageService.java
  src/main/java/com/beanions/user/controller/SignupController.java
  src/main/resources/assets/js/signup.js
  src/main/resources/mapper/mypage/MyPageMapper.xml
  src/main/resources/templates/user/mypage/mypageMyinfo.html
  src/main/resources/templates/user/mypage/mypageReview.html
Labels: feature

#137 [FEATURE][BOARD]게시판 CSS 수정, 글쓰기 기능, 정렬 기능 수정, 페이지네이션 구현 중
  src/main/java/com/beanions/board/free/controller/FreeBoardController.java
  src/main/java/com/beanions/board/free/service/FreeBoardService.java
  src/main/java/com/beanions/board/magazine/dao/MagazineMapper.java
  src/main/java/com/beanions/common/dto/SearchDTO.java
  src/main/resources/mapper/board/FreeBoardMapper.xml
  src/main/resources/mapper/board/MagazineMapper.xml
  src/main/resources/templates/user/board/freeDetail.html
  src/main/resources/templates/user/board/freeList.html
Labels: feature

#143 [FEATURE][ADMIN] 회원 상세 관리 css 추가
  src/main/java/com/beanions/admin/controller/AdminController.java
  src/main/java/com/beanions/admin/dao/AdminMapper.java
  src/main/java/com/beanions/admin/dto/AdminMemberPostDTO.java
  src/main/java/com/beanions/admin/service/AdminMemberService.java
  src/main/resources/assets/css/admin/membersCss.css
  src/main/resources/mapper/admin/AdminMapper.xml
  src/main/resources/templates/admin/member/membersDetail.html
  src/main/resources/templates/admin/member/membersList.html
  src/main/resources/templates/admin/member/membersModify.html
Labels: feature

#145 [FEATURE][SEARCH]검색 결과 페이지 추가
  src/main/java/com/beanions/config/SecurityConfig.java
  src/main/java/com/beanions/search/controller/SearchController.java
  src/main/java/com/beanions/search/dao/SearchMapper.java
  src/main/java/com/beanions/search/service/SearchService.java
  src/main/resources/assets/css/user/search.css
  src/main/resources/templates/user/search/result.html
Labels: feature

#146 [FEATURE][BOARD] 페이지네이션 기능 추가
  src/main/resources/templates/user/board/freeList.html
Labels: feature

#148 [FEATURE][COMMENT] 게시글 상세페이지 내 댓글 레이아웃 및 스크립트 추가
  src/main/java/com/beanions/board/free/controller/FreeBoardController.java
  src/main/resources/assets/css/user/comment.css
  src/main/resources/templates/user/board/freeDetail.html
Labels: feature

#154 [FEATURE][SEARCH] 검색기능 초기 구현
  src/main/java/com/beanions/common/dto/SearchDTO.java
  src/main/java/com/beanions/search/controller/SearchController.java
  src/main/java/com/beanions/search/dao/SearchMapper.java
  src/main/java/com/beanions/search/service/SearchService.java
  src/main/resources/mapper/search/SearchMapper.xml
  src/main/resources/templates/user/main.html
  src/main/resources/templates/user/search/result.html
Labels: feature

#150 [FEATUER][VISITOR] Spring Redis DB를 활용해 세션 및 방문자 수 캐싱 관리
  build.gradle
  src/main/java/com/beanions/auth/dao/UserMapper.java
  src/main/java/com/beanions/auth/model/AuthDetails.java
  src/main/java/com/beanions/common/dto/LoginUserDTO.java
  src/main/java/com/beanions/config/Interceptor/VisitorInterceptor.java
  src/main/java/com/beanions/config/RedisConfig.java
  src/main/java/com/beanions/config/SecurityConfig.java
  src/main/java/com/beanions/config/WebConfig.java
  src/main/java/com/beanions/config/handler/AuthSuccessHandler.java
  src/main/java/com/beanions/main/controller/MainController.java
  src/main/java/com/beanions/user/dao/SignupMapper.java
  src/main/java/com/beanions/user/service/SignupService.java
  src/main/java/com/beanions/user/service/VisitorService.java
  src/main/resources/application.yml
  src/main/resources/assets/css/user/signup.css
  src/main/resources/mapper/user/SignupMapper.xml
  src/main/resources/mapper/user/UserMapper.xml
  src/main/resources/templates/user/signup.html
Labels: feature

#166 [FEATURE][ERRORHANDLER] 에러페이지
  src/main/java/com/beanions/config/handler/GlobalExceptionHandler.java
  src/main/resources/application.yml
  src/main/resources/templates/error/403.html
  src/main/resources/templates/error/404.html
  src/main/resources/templates/error/500.html
  src/main/resources/templates/error/nullPointer.html
Labels: feature

#161 [FEATURE][SEARCH] 상세페이지 연결 및 CSS 적용
  src/main/java/com/beanions/search/controller/SearchController.java
  src/main/resources/assets/css/user/search.css
  src/main/resources/templates/user/search/result.html
Labels: feature

#162 [FEATURE][COMMONSETTING] HEADER 서브 메뉴 관련 마우스 오버시 비정상적 활성화되는 버그 해결
  src/main/resources/assets/css/user/common.css
Labels: feature

#164 [FEATURE][UPLOADFILES] 파일 업로드 관련 기능 작업
  src/main/java/com/beanions/common/dto/UploadFilesDTO.java
  src/main/java/com/beanions/common/uploadfiles/UploadController.java
  src/main/java/com/beanions/common/uploadfiles/UploadService.java
  src/main/java/com/beanions/mypage/controller/MyPageController.java
  src/main/java/com/beanions/mypage/dao/MyPageMapper.java
  src/main/java/com/beanions/mypage/dao/UploadMapper.java
  src/main/java/com/beanions/mypage/service/MyPageService.java
  src/main/resources/application.yml
  src/main/resources/assets/css/summernote/font/summernote.eot
  src/main/resources/assets/css/summernote/font/summernote.ttf
  src/main/resources/assets/css/summernote/font/summernote.woff
  src/main/resources/assets/css/summernote/font/summernote.woff2
  src/main/resources/assets/css/user/writeBoard.css
  src/main/resources/assets/js/summernote/lang/summernote-ko-KR.js
  src/main/resources/assets/js/summernote/lang/summernote-ko-KR.min.js
  src/main/resources/mapper/mypage/MyPageMapper.xml
  src/main/resources/mapper/mypage/UploadMapper.xml
  src/main/resources/templates/user/mypage/fileUpload.html
  src/main/resources/templates/user/mypage/writeBoard.html
Labels: feature, help

#160 [FEATURE][INQUIRY] 문의 메일
  src/main/java/com/beanions/auth/controller/AuthController.java
  src/main/java/com/beanions/config/SecurityConfig.java
  src/main/java/com/beanions/config/handler/AuthFailHandler.java
  src/main/java/com/beanions/main/controller/MainController.java
  src/main/java/com/beanions/user/dto/EmailDTO.java
  src/main/java/com/beanions/user/service/MailService.java
  src/main/resources/assets/js/forgetInfo.js
  src/main/resources/assets/js/main.js
  src/main/resources/templates/auth/login.html
  src/main/resources/templates/user/main.html
Labels: feature

#167 [Feature][pagination] 페이지네이션 게시판에 이식, 매거진 상세 목록 오류 수정
  src/main/java/com/beanions/board/free/controller/FreeBoardController.java
  src/main/java/com/beanions/board/free/dao/FreeBoardMapper.java
  src/main/java/com/beanions/board/free/service/FreeBoardService.java
  src/main/java/com/beanions/board/magazine/controller/MagazineController.java
  src/main/java/com/beanions/board/magazine/dao/MagazineMapper.java
  src/main/java/com/beanions/board/magazine/service/MagazineService.java
  src/main/java/com/beanions/board/notice/controller/NoticeController.java
  src/main/java/com/beanions/board/notice/dao/NoticeMapper.java
  src/main/java/com/beanions/board/notice/service/NoticeService.java
  src/main/java/com/beanions/board/review/controller/ReviewController.java
  src/main/java/com/beanions/board/review/dao/ReviewMapper.java
  src/main/java/com/beanions/board/review/service/ReviewService.java
  src/main/resources/mapper/board/FreeBoardMapper.xml
  src/main/resources/mapper/board/MagazineMapper.xml
  src/main/resources/mapper/board/NoticeMapper.xml
  src/main/resources/mapper/board/ReviewMapper.xml
  src/main/resources/templates/user/board/freeList.html
  src/main/resources/templates/user/board/magazineDetail.html
  src/main/resources/templates/user/board/magazineList.html
  src/main/resources/templates/user/board/noticeList.html
  src/main/resources/templates/user/board/reviewList.html
Labels: feature

#173 [FEATURE][ADMIN] 관리자 Dashboard 방문자 수 조회 기능 추가
  src/main/java/com/beanions/admin/dto/AdminMainDTO.java
  src/main/resources/mapper/admin/AdminMapper.xml
  src/main/resources/templates/admin/main/dashBoard.html
Labels: feature

#172 [FEATURE][MYPAGESESSION] 마이페이지 HEADER 수정
  src/main/resources/templates/user/mypage/mypageMain.html
Labels: feature

#171 [FEATURE][MAGAZINE] 매거진 LIST CSS
  src/main/java/com/beanions/board/common/dto/PostAndFilesDTO.java
  src/main/resources/assets/css/user/board/free.css
  src/main/resources/assets/css/user/board/magazine.css
  src/main/resources/templates/user/board/magazineList.html
Labels: feature

#169 [FEATURE][COMMENT] 댓글 기능 추가 작업
  src/main/resources/assets/js/signup.js
  src/main/resources/templates/user/board/freeDetail.html
  src/main/resources/templates/user/signup.html
Labels: feature

#176 [FEATURE][COMMENTCOPY] 댓글 기능 타 게시글에 옯기기 작업
  src/main/resources/assets/js/comment.js
  src/main/resources/templates/user/board/freeDetail.html
  src/main/resources/templates/user/board/magazineDetail.html
  src/main/resources/templates/user/board/noticeDetail.html
  src/main/resources/templates/user/board/reviewDetail.html
  src/main/resources/templates/user/signup.html
Labels: feature

#183 [FEATURE][ADMIN] 관리자 페이지 전체적으로 수정 및 게시판 관리 리스트 페이지에 검색 기능 추가
  src/main/java/com/beanions/admin/controller/AdminBoardController.java
  src/main/java/com/beanions/admin/dao/AdminMapper.java
  src/main/java/com/beanions/admin/service/AdminService.java
  src/main/resources/assets/css/admin/adminPost.css
  src/main/resources/assets/css/admin/common.css
  src/main/resources/mapper/admin/AdminMapper.xml
  src/main/resources/templates/admin/footer.html
  src/main/resources/templates/admin/header.html
  src/main/resources/templates/admin/magazine/detail.html
  src/main/resources/templates/admin/magazine/regist.html
  src/main/resources/templates/admin/magazine/update.html
  src/main/resources/templates/admin/main/dashBoard.html
  src/main/resources/templates/admin/member/membersList.html
  src/main/resources/templates/admin/notice/detail.html
  src/main/resources/templates/admin/notice/regist.html
  src/main/resources/templates/admin/notice/update.html
  src/main/resources/templates/admin/post/detail.html
  src/main/resources/templates/admin/post/list.html
Labels: bug, feature

#181 [FEATURE][MYPAGE] 마이페이지 레이아웃 및 기능 작업
  src/main/java/com/beanions/mypage/controller/MyPageController.java
  src/main/resources/assets/css/user/mypage.css
  src/main/resources/assets/js/common.js
  src/main/resources/templates/user/mypage/mypageComment.html
  src/main/resources/templates/user/mypage/mypageFree.html
  src/main/resources/templates/user/mypage/mypageMain.html
  src/main/resources/templates/user/mypage/mypageMyinfo.html
  src/main/resources/templates/user/mypage/mypageReview.html
  src/main/resources/templates/user/mypage/mypageSchedule.html
  src/main/resources/templates/user/mypage/mypageScheduleDetail.html
  src/main/resources/templates/user/mypage/mypageScheduleManage.html
  src/main/resources/templates/user/mypage/mypageScheduleRegister.html
Labels: feature, help

#180 [FEATURE][UPLOADFILES] 파일 업로드 관련 기능 작업
  src/main/java/com/beanions/common/uploadfiles/UploadController.java
  src/main/java/com/beanions/common/uploadfiles/UploadService.java
  src/main/java/com/beanions/mypage/dao/UploadMapper.java
  src/main/resources/assets/css/user/writeBoard.css
  src/main/resources/assets/images/common/icon_comment.png
  src/main/resources/assets/images/common/icon_comment_white.png
  src/main/resources/assets/images/common/icon_writing.png
  src/main/resources/assets/images/common/icon_writing_white.png
  src/main/resources/assets/images/upload/user/uploadTemp/10cf4118-cb41-4231-ad70-2bd8e5373304.webp
  src/main/resources/assets/images/upload/user/uploadTemp/2657f337-3573-41b7-a6ea-c6241212a491.png
  src/main/resources/assets/images/upload/user/uploadTemp/ba8102eb-5329-4aed-9cd7-879bc1c8db08.png
  src/main/resources/assets/images/upload/user/uploadTemp/c2227003-8c24-40e4-8f78-0aac7c466791.png
  src/main/resources/assets/images/upload/user/uploadTemp/c29e177c-a197-4cc4-8a35-d79693355c13.jpg
  src/main/resources/assets/images/upload/user/uploadTemp/f63b2fc3-8d83-4991-be4c-47150876709c.webp
  src/main/resources/mapper/mypage/UploadMapper.xml
  src/main/resources/templates/user/mypage/fileUpload.html
Labels: feature, help

#178 [FEATURE][ADMIN] 회원 상세 조회&수정 보완
  src/main/java/com/beanions/admin/controller/AdminController.java
  src/main/java/com/beanions/config/WebConfig.java
  src/main/resources/application.yml
  src/main/resources/assets/css/admin/membersCss.css
  src/main/resources/assets/js/signup.js
  src/main/resources/mapper/admin/AdminMapper.xml
  src/main/resources/templates/admin/member/membersDetail.html
  src/main/resources/templates/admin/member/membersModify.html
Labels: feature

#186 [FEATURE][dockercompose] docker-compose.yml 추가
  docker-compose.yml
  redis/data/dump.rdb
Labels: feature

#187 [FEATURE][ADMIN] postContext 개행 적용 및 공지사항 관리 페이지 검색 기능 추가
  src/main/java/com/beanions/admin/controller/AdminBoardController.java
  src/main/java/com/beanions/admin/dao/AdminMapper.java
  src/main/java/com/beanions/admin/service/AdminService.java
  src/main/resources/assets/css/admin/common.css
  src/main/resources/mapper/admin/AdminMapper.xml
  src/main/resources/templates/admin/notice/detail.html
  src/main/resources/templates/admin/notice/list.html
  src/main/resources/templates/admin/post/list.html
Labels: feature

#197 [FEATURE][COMMONSETTING] FOOTER > ABOUT US / 개인정보처리방침/ 약관정책 페이지 추가 및 FOOTER에 링크 연결
  src/main/java/com/beanions/main/controller/MainController.java
  src/main/resources/assets/css/user/common.css
  src/main/resources/templates/user/layout/about.html
  src/main/resources/templates/user/layout/footer.html
  src/main/resources/templates/user/layout/privacy.html
  src/main/resources/templates/user/layout/terms.html
Labels: feature

#194 [FEATURE][MAIN] 메인 페이지 상단 배너 동적 이미지 변경 및 예피셜 레이아웃 수정 + 이미지 파일 추가
  src/main/resources/assets/css/user/main.css
  src/main/resources/assets/images/main/banner01.png
  src/main/resources/assets/images/main/bg01.png
  src/main/resources/assets/images/main/bg02.png
  src/main/resources/assets/images/main/bg03.png
  src/main/resources/assets/images/main/bg04.png
  src/main/resources/assets/images/main/bg05.png
  src/main/resources/assets/images/main/bg06.png
  src/main/resources/assets/images/main/bg07.png
  src/main/resources/assets/images/main/bg08.png
  src/main/resources/assets/images/main/bg09.png
  src/main/resources/assets/images/main/bg10.png
  src/main/resources/assets/images/main/bg11.png
  src/main/resources/assets/images/main/bg12.png
  src/main/resources/assets/images/main/bg13.png
  src/main/resources/assets/images/main/bg14.png
  src/main/resources/assets/images/main/bg15.png
  src/main/resources/assets/images/main/bg16.png
  src/main/resources/assets/images/main/bg17.png
  src/main/resources/assets/images/main/bg18.png
  src/main/resources/assets/images/main/bg19.png
  src/main/resources/assets/images/main/bg20.png
  src/main/resources/assets/images/main/bg21.png
  src/main/resources/assets/images/main/bg22.png
  src/main/resources/assets/images/main/bg23.png
  src/main/resources/assets/images/main/bg24.png
  src/main/resources/assets/images/main/bg25.png
  src/main/resources/assets/images/main/bg26.png
  src/main/resources/assets/images/main/bg27.png
  src/main/resources/assets/images/main/bg28.png
  src/main/resources/assets/images/main/bg29.png
  src/main/resources/assets/images/main/bg30.png
  src/main/resources/assets/images/main/bg31.png
  src/main/resources/assets/js/main.js
  src/main/resources/templates/user/main.html
Labels: feature

#191 [FEATURE][BOARD] CSS, 게시물 수정 삭제 권한
  src/main/java/com/beanions/board/magazine/controller/MagazineController.java
  src/main/java/com/beanions/board/magazine/controller/Pagination.java
  src/main/java/com/beanions/board/magazine/controller/PagingResponse.java
  src/main/java/com/beanions/board/magazine/dao/MagazineMapper.java
  src/main/java/com/beanions/board/magazine/dto/MagazineDTO.java
  src/main/java/com/beanions/board/magazine/service/MagazineService.java
  src/main/resources/assets/css/user/board/magazine.css
  src/main/resources/assets/images/common/magazine_test.jpg
  src/main/resources/mapper/board/MagazineMapper.xml
  src/main/resources/templates/user/board/freeDetail.html
  src/main/resources/templates/user/board/freeList.html
  src/main/resources/templates/user/board/magazineList.html
  src/main/resources/templates/user/board/noticeList.html
  src/main/resources/templates/user/board/reviewDetail.html
  src/main/resources/templates/user/board/reviewList.html
Labels: feature

#193 [FEATURE][writeUploadFile] 게시글 등록 및 파일 다중 업로드
  src/main/java/com/beanions/board/common/dto/PostAndCommentDTO.java
  src/main/java/com/beanions/board/common/dto/PostAndMemberDTO.java
  src/main/java/com/beanions/board/free/controller/FreeBoardController.java
  src/main/java/com/beanions/board/magazine/controller/MagazineController.java
  src/main/java/com/beanions/board/notice/controller/NoticeController.java
  src/main/java/com/beanions/board/review/controller/ReviewController.java
  src/main/java/com/beanions/common/dto/FilesDTO.java
  src/main/java/com/beanions/common/dto/PostDTO.java
  src/main/java/com/beanions/common/uploadfiles/UploadController.java
  src/main/java/com/beanions/common/uploadfiles/UploadService.java
  src/main/java/com/beanions/config/SecurityConfig.java
  src/main/java/com/beanions/config/WebConfig.java
  src/main/java/com/beanions/mypage/controller/MyPageController.java
  src/main/java/com/beanions/mypage/dao/MyPageMapper.java
  src/main/java/com/beanions/mypage/dao/UploadMapper.java
  src/main/java/com/beanions/mypage/service/MyPageService.java
  src/main/java/com/beanions/user/service/SignupService.java
  src/main/resources/assets/images/upload/user/uploadTemp/10cf4118-cb41-4231-ad70-2bd8e5373304.webp
  src/main/resources/assets/images/upload/user/uploadTemp/2657f337-3573-41b7-a6ea-c6241212a491.png
  src/main/resources/assets/images/upload/user/uploadTemp/ba8102eb-5329-4aed-9cd7-879bc1c8db08.png
  src/main/resources/assets/images/upload/user/uploadTemp/c2227003-8c24-40e4-8f78-0aac7c466791.png
  src/main/resources/assets/images/upload/user/uploadTemp/c29e177c-a197-4cc4-8a35-d79693355c13.jpg
  src/main/resources/assets/images/upload/user/uploadTemp/f63b2fc3-8d83-4991-be4c-47150876709c.webp
  src/main/resources/mapper/admin/AdminMapper.xml
  src/main/resources/mapper/board/FreeBoardMapper.xml
  src/main/resources/mapper/board/MagazineMapper.xml
  src/main/resources/mapper/board/NoticeMapper.xml
  src/main/resources/mapper/board/ReviewMapper.xml
  src/main/resources/mapper/mypage/MyPageMapper.xml
  src/main/resources/mapper/mypage/UploadMapper.xml
  src/main/resources/templates/user/board/freeDetail.html
  src/main/resources/templates/user/board/freeList.html
  src/main/resources/templates/user/board/magazineDetail.html
  src/main/resources/templates/user/board/noticeDetail.html
  src/main/resources/templates/user/board/reviewDetail.html
  src/main/resources/templates/user/board/reviewList.html
  src/main/resources/templates/user/layout/header.html
  src/main/resources/templates/user/mypage/fileUpload.html
Labels: feature

#198 [FEATURE][ADMIN] 관리자 페이지 상세 페이지 개행 적용
  src/main/java/com/beanions/admin/controller/AdminBoardController.java
  src/main/resources/assets/css/admin/adminPost.css
  src/main/resources/mapper/admin/AdminMapper.xml
  src/main/resources/templates/admin/magazine/detail.html
  src/main/resources/templates/admin/notice/regist.html
  src/main/resources/templates/admin/notice/update.html
  src/main/resources/templates/admin/post/detail.html
Labels: feature

#204 [FEATURE][ADMIN] 공지사항 관리 등록, 수정 시 제목&내용 글자수 제한 추가
  src/main/resources/assets/css/admin/adminPost.css
  src/main/resources/assets/css/admin/common.css
  src/main/resources/templates/admin/notice/regist.html
  src/main/resources/templates/admin/notice/update.html
Labels: feature

#203 [FEATURE][UPLOADFILE_MODIFIED] 업로드 파일 fileupload.html 및 게시물 상세 페이지 레이아웃 수정
  src/main/java/com/beanions/board/free/controller/FreeBoardController.java
  src/main/java/com/beanions/board/review/controller/ReviewController.java
  src/main/java/com/beanions/common/uploadfiles/UploadController.java
  src/main/resources/assets/css/user/board/free.css
  src/main/resources/assets/css/user/board/magazine.css
  src/main/resources/assets/css/user/board/notice.css
  src/main/resources/assets/css/user/board/review.css
  src/main/resources/assets/css/user/writeBoard.css
  src/main/resources/assets/images/upload/user/upload/uploadTempImg.jpg
  src/main/resources/templates/user/board/freeDetail.html
  src/main/resources/templates/user/board/reviewDetail.html
  src/main/resources/templates/user/mypage/fileUpload.html
  src/main/resources/templates/user/mypage/mypageReview.html
  src/main/resources/templates/user/mypage/mypageScheduleRegister.html
Labels: feature

#200 [Hotfix][upload] 파일 다중 업로드 버그 이슈
  src/main/java/com/beanions/common/uploadfiles/UploadController.java
  src/main/resources/assets/images/upload/user/upload/uploadTempImg.jpg
  src/main/resources/templates/user/mypage/fileUpload.html
Labels: bug, hotfix

#205 [FEATURE][ADMINDETAILFILE] 관리자 상세 페이지 이미지 출력
  src/main/java/com/beanions/admin/controller/AdminBoardController.java
  src/main/java/com/beanions/admin/dto/AdminPostDTO.java
  src/main/resources/mapper/admin/AdminMapper.xml
  src/main/resources/templates/admin/magazine/detail.html
  src/main/resources/templates/admin/post/detail.html
  src/main/resources/templates/user/signup.html
Labels: feature

#208 [FEATURE][BOARD] 게시물 상세조회 페이지 개행 적용
  src/main/java/com/beanions/admin/controller/AdminBoardController.java
  src/main/java/com/beanions/board/free/controller/FreeBoardController.java
  src/main/java/com/beanions/board/free/dao/FreeBoardMapper.java
  src/main/java/com/beanions/board/free/service/FreeBoardService.java
  src/main/java/com/beanions/board/magazine/controller/MagazineController.java
  src/main/java/com/beanions/board/magazine/dao/MagazineMapper.java
  src/main/java/com/beanions/board/magazine/service/MagazineService.java
  src/main/java/com/beanions/board/notice/controller/NoticeController.java
  src/main/java/com/beanions/board/notice/dao/NoticeMapper.java
  src/main/java/com/beanions/board/notice/service/NoticeService.java
  src/main/java/com/beanions/board/review/controller/ReviewController.java
  src/main/java/com/beanions/board/review/dao/ReviewMapper.java
  src/main/java/com/beanions/board/review/service/ReviewService.java
  src/main/resources/assets/css/admin/common.css
  src/main/resources/mapper/admin/AdminMapper.xml
  src/main/resources/templates/admin/magazine/detail.html
  src/main/resources/templates/admin/magazine/list.html
  src/main/resources/templates/admin/magazine/regist.html
  src/main/resources/templates/admin/magazine/update.html
  src/main/resources/templates/admin/member/membersList.html
  src/main/resources/templates/admin/notice/detail.html
  src/main/resources/templates/admin/notice/regist.html
  src/main/resources/templates/admin/notice/update.html
  src/main/resources/templates/admin/post/detail.html
  src/main/resources/templates/user/board/freeDetail.html
  src/main/resources/templates/user/board/magazineDetail.html
  src/main/resources/templates/user/board/noticeDetail.html
Labels: feature

#211 [FEATURE][MYPAGE] 마이페이지 댓글 페이지에서 상세페이지 연결
  src/main/resources/templates/user/mypage/mypageComment.html
Labels: feature

#212 [FEATURE][MYPAGE/MYINFO] 마이페이지 내 정보 수정
  src/main/java/com/beanions/mypage/controller/MyPageController.java
  src/main/java/com/beanions/mypage/dao/MyPageMapper.java
  src/main/java/com/beanions/mypage/service/MyPageService.java
  src/main/resources/assets/js/comment.js
  src/main/resources/assets/js/mypage.js
  src/main/resources/mapper/mypage/MyPageMapper.xml
  src/main/resources/templates/user/mypage/mypageMyinfo.html
Labels: feature

#214 [FEATURE][MODAL] 모달창
  src/main/resources/assets/css/user/board/free.css
  src/main/resources/templates/user/board/freeList.html
  src/main/resources/templates/user/board/freeModify.html
Labels: feature

#217 [FEATURE][MODAL] 모달/팝업창 레이아웃 및 스크립트 작업 to 회원가입 페이지
  src/main/resources/assets/css/user/signup.css
  src/main/resources/assets/js/signup.js
  src/main/resources/assets/js/summernote/lang/summernote-ko-KR.js
  src/main/resources/assets/js/summernote/lang/summernote-ko-KR.min.js
  src/main/resources/templates/user/signup.html
Labels: feature

#218 [FEATURE][URL] 요청 URL 점검
  src/main/java/com/beanions/board/free/controller/FreeBoardController.java
  src/main/java/com/beanions/board/review/controller/ReviewController.java
  src/main/java/com/beanions/common/dto/SearchDTO.java
  src/main/java/com/beanions/config/SecurityConfig.java
  src/main/java/com/beanions/config/handler/AuthSuccessHandler.java
  src/main/java/com/beanions/config/handler/LogoutHandler.java
  src/main/resources/assets/css/admin/common.css
  src/main/resources/templates/admin/magazine/detail.html
  src/main/resources/templates/admin/post/detail.html
  src/main/resources/templates/user/board/freeList.html
  src/main/resources/templates/user/board/magazineList.html
  src/main/resources/templates/user/board/noticeList.html
  src/main/resources/templates/user/board/reviewDetail.html
  src/main/resources/templates/user/board/reviewList.html
  src/main/resources/templates/user/layout/header.html
  src/main/resources/templates/user/main.html
  src/main/resources/templates/user/mypage/mypageComment.html
  src/main/resources/templates/user/mypage/mypageFree.html
  src/main/resources/templates/user/mypage/mypageReview.html
  src/main/resources/templates/user/search/result.html
Labels: feature, hotfix

#220 [FEATURE][MAIN] CLIENT 페이지 내 파비콘 및 타이틀 변경 & 댓글 레이아웃 수정 작업
  src/main/resources/assets/js/comment.js
  src/main/resources/templates/auth/fail.html
  src/main/resources/templates/auth/forgetInfo.html
  src/main/resources/templates/auth/login.html
  src/main/resources/templates/user/board/freeDetail.html
  src/main/resources/templates/user/board/freeList.html
  src/main/resources/templates/user/board/freeModify.html
  src/main/resources/templates/user/board/freeRegist.html
  src/main/resources/templates/user/board/magazineDetail.html
  src/main/resources/templates/user/board/magazineList.html
  src/main/resources/templates/user/board/noticeDetail.html
  src/main/resources/templates/user/board/noticeList.html
  src/main/resources/templates/user/board/reviewDetail.html
  src/main/resources/templates/user/board/reviewList.html
  src/main/resources/templates/user/board/reviewModify.html
  src/main/resources/templates/user/layout/about.html
  src/main/resources/templates/user/layout/privacy.html
  src/main/resources/templates/user/layout/terms.html
  src/main/resources/templates/user/main.html
  src/main/resources/templates/user/mypage/fileUpload.html
  src/main/resources/templates/user/mypage/mypageComment.html
  src/main/resources/templates/user/mypage/mypageFree.html
  src/main/resources/templates/user/mypage/mypageMain.html
  src/main/resources/templates/user/mypage/mypageMyinfo.html
  src/main/resources/templates/user/mypage/mypageReview.html
  src/main/resources/templates/user/mypage/mypageSchedule.html
  src/main/resources/templates/user/mypage/mypageScheduleDetail.html
  src/main/resources/templates/user/mypage/mypageScheduleManage.html
  src/main/resources/templates/user/mypage/mypageScheduleRegister.html
  src/main/resources/templates/user/search/result.html
  src/main/resources/templates/user/signup.html
Labels: feature

#221 [FEATURE][ADMIN] 매거진 등록, 수정 페이지 - 글자수제한 적용 및 관리자 페이지 파비콘 적용
  src/main/java/com/beanions/admin/controller/AdminBoardController.java
  src/main/java/com/beanions/admin/dao/AdminMapper.java
  src/main/java/com/beanions/admin/service/AdminService.java
  src/main/resources/mapper/admin/AdminMapper.xml
  src/main/resources/templates/admin/magazine/detail.html
  src/main/resources/templates/admin/magazine/list.html
  src/main/resources/templates/admin/magazine/regist.html
  src/main/resources/templates/admin/magazine/update.html
  src/main/resources/templates/admin/main/dashBoard.html
  src/main/resources/templates/admin/member/membersDetail.html
  src/main/resources/templates/admin/member/membersList.html
  src/main/resources/templates/admin/member/membersModify.html
  src/main/resources/templates/admin/notice/detail.html
  src/main/resources/templates/admin/notice/list.html
  src/main/resources/templates/admin/notice/regist.html
  src/main/resources/templates/admin/notice/update.html
  src/main/resources/templates/admin/post/detail.html
  src/main/resources/templates/admin/post/list.html
  src/main/resources/templates/auth/forgetInfo.html
  src/main/resources/templates/auth/login.html
  src/main/resources/templates/error/403.html
  src/main/resources/templates/error/404.html
  src/main/resources/templates/error/500.html
  src/main/resources/templates/user/layout/about.html
  src/main/resources/templates/user/layout/footer.html
  src/main/resources/templates/user/layout/header.html
Labels: feature

#216 [FEATURE][ADMIN] 회원 상세 검색
  src/main/java/com/beanions/admin/controller/AdminController.java
  src/main/java/com/beanions/admin/dao/AdminMapper.java
  src/main/java/com/beanions/admin/service/AdminMemberService.java
  src/main/resources/mapper/admin/AdminMapper.xml
  src/main/resources/templates/admin/member/membersList.html
Labels: feature

#223 [FEATURE][MODAL] 자유 게시판 수정 모달창
  src/main/resources/assets/css/user/board/free.css
  src/main/resources/templates/user/board/freeModify.html
  src/main/resources/templates/user/board/reviewDetail.html
Labels: feature

#225 [FEATURE][ADMINMAGAZINEUPLOAD] 관리자 매거진 게시글 파일 다중 업로드
  src/main/java/com/beanions/common/uploadfiles/UploadController.java
  src/main/java/com/beanions/common/uploadfiles/UploadService.java
  src/main/java/com/beanions/mypage/dao/UploadMapper.java
  src/main/resources/application.yml
  src/main/resources/assets/css/admin/common.css
  src/main/resources/assets/js/adminFileModify.js
  src/main/resources/assets/js/adminFileUpload.js
  src/main/resources/assets/js/jsTemp.js
  src/main/resources/mapper/mypage/UploadMapper.xml
  src/main/resources/templates/admin/magazine/list.html
  src/main/resources/templates/admin/magazine/regist.html
  src/main/resources/templates/admin/magazine/update.html
Labels: feature

#226 ## 회원가입/로그인 오류 수정
  src/main/resources/assets/css/user/mypage.css
  src/main/resources/assets/js/signup.js
  src/main/resources/templates/auth/fail.html
  src/main/resources/templates/user/signup.html
Labels: bug, hotfix

#224 [FEATURE][BOARDEDIT] REVIEW 수정 모달창, PostMapping 주소 변경, 헤더 common.js 변경
  src/main/java/com/beanions/board/free/controller/FreeBoardController.java
  src/main/resources/assets/css/user/board/review.css
  src/main/resources/templates/user/board/freeModify.html
  src/main/resources/templates/user/board/freeRegist.html
  src/main/resources/templates/user/board/reviewList.html
  src/main/resources/templates/user/board/reviewModify.html
Labels: feature

#231 [FEATURE][ADMIN] 회원 상세 조회 페이지 수정
  src/main/resources/templates/admin/member/membersDetail.html
Labels: feature

#229 [FEATURE][ADMIN&REVIEW] 관리자 매거진 기능 수정 및 리뷰페이지 이슈 해결
  src/main/java/com/beanions/admin/controller/AdminBoardController.java
  src/main/resources/assets/css/admin/adminWriteBoard.css
  src/main/resources/assets/js/adminFileUpload.js
  src/main/resources/mapper/mypage/UploadMapper.xml
  src/main/resources/templates/admin/magazine/regist.html
  src/main/resources/templates/admin/magazine/update.html
  src/main/resources/templates/user/board/reviewDetail.html
Labels: bug, feature, hotfix

#227 [FEATURE][MYPAGE/MYINFO] 마이페이지 > 회원정보수정 - 회원탈퇴 적용/게시판 상세 페이지 내 모달 위치 수정
  src/main/java/com/beanions/mypage/controller/MyPageController.java
  src/main/java/com/beanions/mypage/dao/MyPageMapper.java
  src/main/java/com/beanions/mypage/service/MyPageService.java
  src/main/resources/assets/css/user/board/free.css
  src/main/resources/assets/css/user/board/review.css
  src/main/resources/assets/css/user/mypage.css
  src/main/resources/assets/js/mypage.js
  src/main/resources/mapper/mypage/MyPageMapper.xml
  src/main/resources/templates/user/board/freeDetail.html
  src/main/resources/templates/user/board/freeList.html
  src/main/resources/templates/user/board/reviewDetail.html
  src/main/resources/templates/user/layout/privacy.html
  src/main/resources/templates/user/layout/terms.html
  src/main/resources/templates/user/mypage/mypageComment.html
  src/main/resources/templates/user/mypage/mypageFree.html
  src/main/resources/templates/user/mypage/mypageMyinfo.html
  src/main/resources/templates/user/mypage/mypageReview.html
Labels: feature
